// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApE5SkRt8Mk_B6I1vqIVwt53PutmLYK88',
    appId: '1:920535675660:android:73bcd1c2c0d7a749340f29',
    messagingSenderId: '920535675660',
    projectId: 'datn-chinh',
    storageBucket: 'datn-chinh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_TShaBVdRvK_11CkCyavAA3Kf5O2uG18',
    appId: '1:920535675660:ios:f568b15e39b2439d340f29',
    messagingSenderId: '920535675660',
    projectId: 'datn-chinh',
    storageBucket: 'datn-chinh.appspot.com',
    iosBundleId: 'com.example.datnTrung',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG6DPjgh1pvh3cSpknSY96LR2gl2L5T0g',
    appId: '1:920535675660:web:39dd284d7c2d75d0340f29',
    messagingSenderId: '920535675660',
    projectId: 'datn-chinh',
    authDomain: 'datn-chinh.firebaseapp.com',
    storageBucket: 'datn-chinh.appspot.com',
    measurementId: 'G-1B95V5TZXW',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_TShaBVdRvK_11CkCyavAA3Kf5O2uG18',
    appId: '1:920535675660:ios:f568b15e39b2439d340f29',
    messagingSenderId: '920535675660',
    projectId: 'datn-chinh',
    storageBucket: 'datn-chinh.appspot.com',
    iosBundleId: 'com.example.datnTrung',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG6DPjgh1pvh3cSpknSY96LR2gl2L5T0g',
    appId: '1:920535675660:web:8455afd71c59526e340f29',
    messagingSenderId: '920535675660',
    projectId: 'datn-chinh',
    authDomain: 'datn-chinh.firebaseapp.com',
    storageBucket: 'datn-chinh.appspot.com',
    measurementId: 'G-P1F67S97FD',
  );

}