// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX6jL6oy1RMioXy0sfGQQZIzWN9eApPtc',
    appId: '1:79495650459:android:297aeebd09815f2d1f3a3e',
    messagingSenderId: '79495650459',
    projectId: 'energymonitor-61619',
    databaseURL: 'https://energymonitor-61619-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'energymonitor-61619.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQs1QOsPRSSXSecSrEaZrEg40rLuShpbE',
    appId: '1:79495650459:ios:7dd13d5c9272f2bd1f3a3e',
    messagingSenderId: '79495650459',
    projectId: 'energymonitor-61619',
    databaseURL: 'https://energymonitor-61619-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'energymonitor-61619.appspot.com',
    iosBundleId: 'com.example.datnTrung',
  );
}
